import 'dart:io';

import 'package:postgres/postgres.dart';
import 'package:shilpa_api/location_menu_scoping.dart';
import 'package:shilpa_api/postgres_app_db.dart';
import 'package:test/test.dart';

/// VPS startup regression: cloning must not hit global UNIQUE on combo.name /
/// raw_materials.barcode (UniqueViolationException → process exit).
///
/// Run manually with a disposable database:
/// POSTGRES_TEST_URL=postgres://user:pass@127.0.0.1:5432/dbname dart test test/location_menu_startup_test.dart
void main() {
  final url = Platform.environment['POSTGRES_TEST_URL'];
  if (url == null || url.isEmpty) {
    test(
      'Postgres migration clones shared menu names across locations',
      () {},
      skip: 'Set POSTGRES_TEST_URL to run',
    );
    return;
  }

  test('migrateMenuCatalogToLocationScope completes with global UNIQUE constraints',
      () async {
    final uri = Uri.parse(url);
    final endpoint = Endpoint(
      host: uri.host,
      port: uri.hasPort ? uri.port : 5432,
      database: uri.pathSegments.isEmpty ? 'postgres' : uri.pathSegments.last,
      username: uri.userInfo.split(':').first,
      password: uri.userInfo.contains(':')
          ? uri.userInfo.split(':').skip(1).join(':')
          : '',
    );

    final conn = await Connection.open(
      endpoint,
      settings: const ConnectionSettings(sslMode: SslMode.disable),
    );
    addTearDown(conn.close);

    await conn.execute('DROP SCHEMA IF EXISTS public CASCADE');
    await conn.execute('CREATE SCHEMA public');

    await conn.execute('''
      CREATE TABLE locations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL
      )
    ''');
    await conn.execute('''
      CREATE TABLE raw_materials (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        barcode TEXT UNIQUE,
        name TEXT NOT NULL,
        sub_item TEXT,
        qty_needed DOUBLE PRECISION NOT NULL DEFAULT 1,
        opening_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
        opening_pieces DOUBLE PRECISION NOT NULL DEFAULT 0,
        current_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
        reorder_level DOUBLE PRECISION NOT NULL DEFAULT 0,
        listed INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
      )
    ''');
    await conn.execute('''
      CREATE TABLE combos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        barcode TEXT,
        price DOUBLE PRECISION NOT NULL DEFAULT 0,
        selling_price DOUBLE PRECISION NOT NULL DEFAULT 0,
        is_active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
      )
    ''');
    await conn.execute('''
      CREATE TABLE combo_raw_materials (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        combo_id INTEGER NOT NULL REFERENCES combos (id) ON DELETE CASCADE,
        raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id) ON DELETE CASCADE,
        qty DOUBLE PRECISION NOT NULL DEFAULT 1
      )
    ''');
    await conn.execute('''
      CREATE TABLE location_stock (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        location_id INTEGER NOT NULL,
        raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id) ON DELETE CASCADE,
        current_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
        opening_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
        reorder_level DOUBLE PRECISION NOT NULL DEFAULT 0,
        UNIQUE(location_id, raw_material_id)
      )
    ''');
    await conn.execute('''
      CREATE TABLE purchases (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        purchase_date TEXT NOT NULL,
        total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
        location_id INTEGER
      )
    ''');
    await conn.execute('''
      CREATE TABLE purchase_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        purchase_id INTEGER NOT NULL REFERENCES purchases (id) ON DELETE CASCADE,
        raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id),
        qty DOUBLE PRECISION NOT NULL,
        rate DOUBLE PRECISION NOT NULL,
        amount DOUBLE PRECISION NOT NULL
      )
    ''');
    await conn.execute('''
      CREATE TABLE sales (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_date TEXT NOT NULL,
        subtotal DOUBLE PRECISION NOT NULL,
        tax DOUBLE PRECISION NOT NULL DEFAULT 0,
        discount DOUBLE PRECISION NOT NULL DEFAULT 0,
        total DOUBLE PRECISION NOT NULL,
        payment_type TEXT NOT NULL,
        location_id INTEGER
      )
    ''');
    await conn.execute('''
      CREATE TABLE sale_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sale_id INTEGER NOT NULL REFERENCES sales (id) ON DELETE CASCADE,
        raw_material_id INTEGER REFERENCES raw_materials (id),
        combo_id INTEGER,
        item_name TEXT NOT NULL,
        qty DOUBLE PRECISION NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        amount DOUBLE PRECISION NOT NULL
      )
    ''');
    await conn.execute('''
      CREATE TABLE stock_ledger (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id),
        entry_date TEXT NOT NULL,
        ref_type TEXT NOT NULL,
        ref_id INTEGER,
        qty_in DOUBLE PRECISION NOT NULL DEFAULT 0,
        qty_out DOUBLE PRECISION NOT NULL DEFAULT 0,
        balance_after DOUBLE PRECISION NOT NULL,
        location_id INTEGER
      )
    ''');
    await conn.execute('''
      CREATE TABLE stock_batches (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id) ON DELETE CASCADE,
        qty_remaining DOUBLE PRECISION NOT NULL,
        location_id INTEGER,
        created_at TEXT NOT NULL
      )
    ''');
    await conn.execute('''
      CREATE TABLE stock_adjustments (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id),
        adjust_date TEXT NOT NULL,
        qty DOUBLE PRECISION NOT NULL,
        reason TEXT,
        location_id INTEGER
      )
    ''');

    final now = DateTime.now().toIso8601String();
    await conn.execute(
      Sql('INSERT INTO locations (name, created_at) VALUES (\$1, \$2)'),
      parameters: ['Location A', now],
    );
    await conn.execute(
      Sql('INSERT INTO locations (name, created_at) VALUES (\$1, \$2)'),
      parameters: ['Location B', now],
    );
    await conn.execute(
      Sql(
        'INSERT INTO raw_materials (barcode, name, sub_item, created_at) '
        'VALUES (\$1, \$2, \$2, \$3)',
      ),
      parameters: ['TEA-001', 'Tea', now],
    );
    await conn.execute(
      Sql(
        'INSERT INTO combos (name, price, selling_price, created_at) '
        'VALUES (\$1, 99, 99, \$2)',
      ),
      parameters: ['Big juicy burger', now],
    );

    await migrateMenuCatalogToLocationScope(
      PostgresAppDb(conn, connection: conn),
    );

    final combos = await conn.execute('SELECT COUNT(*)::int FROM combos');
    expect(combos.first.first, 2);

    final materials = await conn.execute('SELECT COUNT(*)::int FROM raw_materials');
    expect(materials.first.first, 2);

    final applied = await conn.execute(
      Sql(
        "SELECT COUNT(*)::int FROM schema_migrations "
        "WHERE name = 'location_menu_catalog_scope_v1'",
      ),
    );
    expect(applied.first.first, 1);
  });
}
