/// PostgreSQL stock integrity: audit log, CHECK constraints, save tracing.
const postgresStockIntegrityStatements = <String>[
  '''
  CREATE TABLE IF NOT EXISTS stock_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    raw_material_id INTEGER NOT NULL,
    field_name TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    db_user TEXT NOT NULL DEFAULT CURRENT_USER,
    change_source TEXT
  )
  ''',
  '''
  CREATE INDEX IF NOT EXISTS idx_stock_audit_log_material
  ON stock_audit_log (raw_material_id, changed_at DESC)
  ''',
  'ALTER TABLE stock_audit_log ADD COLUMN IF NOT EXISTS change_source TEXT',
  'ALTER TABLE stock_audit_log ADD COLUMN IF NOT EXISTS table_name TEXT',
  '''
  CREATE TABLE IF NOT EXISTS inventory_save_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation TEXT NOT NULL,
    raw_material_id INTEGER,
    success INTEGER NOT NULL DEFAULT 1,
    error_message TEXT,
    created_at TEXT NOT NULL
  )
  ''',
  '''
  DO $$ BEGIN
    ALTER TABLE raw_materials ADD CONSTRAINT chk_current_stock_range
      CHECK (current_stock >= -1000 AND current_stock < 100000);
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$
  ''',
  '''
  DO $$ BEGIN
    ALTER TABLE raw_materials ADD CONSTRAINT chk_opening_stock_range
      CHECK (opening_stock >= -1000 AND opening_stock < 100000);
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$
  ''',
  '''
  DO $$ BEGIN
    ALTER TABLE raw_materials ADD CONSTRAINT chk_opening_pieces_range
      CHECK (opening_pieces >= -1000 AND opening_pieces < 100000);
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$
  ''',
  '''
  DO $$ BEGIN
    ALTER TABLE raw_materials ADD CONSTRAINT chk_units_per_packet_positive
      CHECK (units_per_packet IS NULL OR units_per_packet > 0);
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$
  ''',
  '''
  DO $$ BEGIN
    ALTER TABLE location_stock ADD CONSTRAINT chk_location_current_stock_range
      CHECK (current_stock >= -1000 AND current_stock < 100000);
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$
  ''',
  '''
  DO $$ BEGIN
    ALTER TABLE location_stock ADD CONSTRAINT chk_location_opening_stock_range
      CHECK (opening_stock >= -1000 AND opening_stock < 100000);
  EXCEPTION WHEN duplicate_object THEN NULL;
  END $$
  ''',
  '''
  CREATE OR REPLACE FUNCTION log_raw_materials_stock_audit()
  RETURNS TRIGGER AS $$
  DECLARE
    src TEXT := current_setting('app.change_source', true);
  BEGIN
    IF TG_OP <> 'UPDATE' THEN
      RETURN NEW;
    END IF;

    IF NEW.current_stock IS DISTINCT FROM OLD.current_stock THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'raw_materials', NEW.id, 'current_stock',
        OLD.current_stock::TEXT, NEW.current_stock::TEXT, CURRENT_USER, src
      );
    END IF;

    IF NEW.opening_stock IS DISTINCT FROM OLD.opening_stock THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'raw_materials', NEW.id, 'opening_stock',
        OLD.opening_stock::TEXT, NEW.opening_stock::TEXT, CURRENT_USER, src
      );
    END IF;

    IF NEW.opening_pieces IS DISTINCT FROM OLD.opening_pieces THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'raw_materials', NEW.id, 'opening_pieces',
        OLD.opening_pieces::TEXT, NEW.opening_pieces::TEXT, CURRENT_USER, src
      );
    END IF;

    IF NEW.listed IS DISTINCT FROM OLD.listed THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'raw_materials', NEW.id, 'listed',
        OLD.listed::TEXT, NEW.listed::TEXT, CURRENT_USER, src
      );
    END IF;

    IF NEW.stock_source_id IS DISTINCT FROM OLD.stock_source_id THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'raw_materials', NEW.id, 'stock_source_id',
        OLD.stock_source_id::TEXT, NEW.stock_source_id::TEXT, CURRENT_USER, src
      );
    END IF;

    IF NEW.units_per_packet IS DISTINCT FROM OLD.units_per_packet THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'raw_materials', NEW.id, 'units_per_packet',
        OLD.units_per_packet::TEXT, NEW.units_per_packet::TEXT, CURRENT_USER, src
      );
    END IF;

    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql
  ''',
  '''
  DROP TRIGGER IF EXISTS trg_raw_materials_stock_audit ON raw_materials
  ''',
  '''
  CREATE TRIGGER trg_raw_materials_stock_audit
  AFTER UPDATE ON raw_materials
  FOR EACH ROW
  EXECUTE PROCEDURE log_raw_materials_stock_audit()
  ''',
  '''
  CREATE OR REPLACE FUNCTION log_location_stock_audit()
  RETURNS TRIGGER AS $$
  DECLARE
    src TEXT := current_setting('app.change_source', true);
  BEGIN
    IF TG_OP <> 'UPDATE' THEN
      RETURN NEW;
    END IF;

    IF NEW.current_stock IS DISTINCT FROM OLD.current_stock THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'location_stock', NEW.raw_material_id, 'current_stock',
        OLD.current_stock::TEXT, NEW.current_stock::TEXT, CURRENT_USER, src
      );
    END IF;

    IF NEW.opening_stock IS DISTINCT FROM OLD.opening_stock THEN
      INSERT INTO stock_audit_log (
        table_name, raw_material_id, field_name, old_value, new_value, db_user, change_source
      ) VALUES (
        'location_stock', NEW.raw_material_id, 'opening_stock',
        OLD.opening_stock::TEXT, NEW.opening_stock::TEXT, CURRENT_USER, src
      );
    END IF;

    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql
  ''',
  '''
  DROP TRIGGER IF EXISTS trg_location_stock_audit ON location_stock
  ''',
  '''
  CREATE TRIGGER trg_location_stock_audit
  AFTER UPDATE ON location_stock
  FOR EACH ROW
  EXECUTE PROCEDURE log_location_stock_audit()
  ''',
];

/// One-time report of stock-group mismatches (does not mutate catalog rows).
const postgresStockGroupMismatchReportV1 = 'postgres_stock_group_mismatch_report_v1';

const postgresStockGroupMismatchReportSql = '''
INSERT INTO app_meta (key, value)
SELECT
  'stock_group_mismatch_report',
  COALESCE(
    (
      SELECT json_agg(row_to_json(m))::TEXT
      FROM (
        SELECT
          rm.location_id,
          lower(trim(coalesce(nullif(trim(rm.sub_item), ''), rm.name))) AS stock_key,
          rm.id AS item_id,
          rm.name AS item_name,
          rm.unit_id,
          rm.units_per_packet
        FROM raw_materials rm
        WHERE EXISTS (
          SELECT 1
          FROM raw_materials sib
          WHERE sib.location_id IS NOT DISTINCT FROM rm.location_id
            AND lower(trim(coalesce(nullif(trim(sib.sub_item), ''), sib.name)))
              = lower(trim(coalesce(nullif(trim(rm.sub_item), ''), rm.name)))
            AND sib.id <> rm.id
            AND (
              (rm.unit_id IS NOT NULL AND sib.unit_id IS NOT NULL AND rm.unit_id <> sib.unit_id)
              OR (
                (rm.units_per_packet IS NOT NULL AND rm.units_per_packet > 0)
                <> (sib.units_per_packet IS NOT NULL AND sib.units_per_packet > 0)
              )
            )
        )
        ORDER BY stock_key, rm.location_id, rm.id
      ) m
    ),
    '[]'
  )
WHERE NOT EXISTS (
  SELECT 1 FROM app_meta WHERE key = 'stock_group_mismatch_report'
)
''';
