const postgresSchemaStatements = <String>[
  '''
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    created_at TEXT NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL DEFAULT 'raw_material'
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS units (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    short_code TEXT NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS suppliers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mobile TEXT,
    city TEXT,
    created_at TEXT NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    credit_limit DOUBLE PRECISION NOT NULL DEFAULT 0,
    opening_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS raw_materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode TEXT UNIQUE,
    name TEXT NOT NULL,
    sub_item TEXT,
    qty_needed DOUBLE PRECISION NOT NULL DEFAULT 1,
    category_id INTEGER REFERENCES categories (id),
    unit_id INTEGER REFERENCES units (id),
    image_path TEXT,
    opening_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
    current_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
    reorder_level DOUBLE PRECISION NOT NULL DEFAULT 0,
    shelf_life_days INTEGER,
    units_per_packet DOUBLE PRECISION,
    entry_password_hash TEXT,
    cost_price DOUBLE PRECISION,
    selling_price DOUBLE PRECISION,
    listed INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS stock_batches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id) ON DELETE CASCADE,
    qty_remaining DOUBLE PRECISION NOT NULL,
    rate DOUBLE PRECISION,
    expiry_date TEXT,
    purchase_item_id INTEGER,
    created_at TEXT NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS purchases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER REFERENCES suppliers (id),
    invoice_no TEXT,
    purchase_date TEXT NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS purchase_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id INTEGER NOT NULL REFERENCES purchases (id) ON DELETE CASCADE,
    raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id),
    qty DOUBLE PRECISION NOT NULL,
    rate DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    expiry_date TEXT
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS stock_adjustments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id),
    adjust_date TEXT NOT NULL,
    qty DOUBLE PRECISION NOT NULL,
    reason TEXT
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS stock_ledger (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id),
    entry_date TEXT NOT NULL,
    ref_type TEXT NOT NULL,
    ref_id INTEGER,
    qty_in DOUBLE PRECISION NOT NULL DEFAULT 0,
    qty_out DOUBLE PRECISION NOT NULL DEFAULT 0,
    unit_cost DOUBLE PRECISION,
    balance_after DOUBLE PRECISION NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER REFERENCES customers (id),
    sale_date TEXT NOT NULL,
    subtotal DOUBLE PRECISION NOT NULL,
    tax DOUBLE PRECISION NOT NULL DEFAULT 0,
    discount DOUBLE PRECISION NOT NULL DEFAULT 0,
    total DOUBLE PRECISION NOT NULL,
    payment_type TEXT NOT NULL,
    is_voided INTEGER NOT NULL DEFAULT 0,
    voided_reason TEXT,
    voided_at TEXT
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS sale_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL REFERENCES sales (id) ON DELETE CASCADE,
    raw_material_id INTEGER REFERENCES raw_materials (id),
    combo_id INTEGER,
    item_name TEXT NOT NULL,
    sub_item TEXT,
    qty DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS combos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    barcode TEXT,
    category_id INTEGER REFERENCES categories (id),
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    selling_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    image_path TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS combo_raw_materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_id INTEGER NOT NULL REFERENCES combos (id) ON DELETE CASCADE,
    raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id) ON DELETE CASCADE,
    qty DOUBLE PRECISION NOT NULL DEFAULT 1
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS combo_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_id INTEGER NOT NULL REFERENCES combos (id) ON DELETE CASCADE,
    raw_material_id INTEGER NOT NULL REFERENCES raw_materials (id) ON DELETE CASCADE,
    qty DOUBLE PRECISION NOT NULL DEFAULT 1
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS customer_ledger (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customers (id),
    entry_date TEXT NOT NULL,
    type TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    balance_after DOUBLE PRECISION NOT NULL,
    ref_sale_id INTEGER
  )
  ''',
  '''
  CREATE TABLE IF NOT EXISTS app_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
  )
  ''',
  'CREATE INDEX IF NOT EXISTS idx_raw_materials_name ON raw_materials(name)',
  'CREATE INDEX IF NOT EXISTS idx_raw_materials_barcode ON raw_materials(barcode)',
  'CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id)',
  'CREATE INDEX IF NOT EXISTS idx_sale_items_material ON sale_items(raw_material_id)',
  'CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase ON purchase_items(purchase_id)',
  'CREATE INDEX IF NOT EXISTS idx_stock_ledger_material ON stock_ledger(raw_material_id)',
  'CREATE INDEX IF NOT EXISTS idx_customer_ledger_customer ON customer_ledger(customer_id)',
  'CREATE INDEX IF NOT EXISTS idx_combo_raw_materials_combo ON combo_raw_materials(combo_id)',
  'CREATE INDEX IF NOT EXISTS idx_stock_batches_fefo ON stock_batches (raw_material_id, expiry_date)',
  'ALTER TABLE sale_items ALTER COLUMN raw_material_id DROP NOT NULL',
  '''
  INSERT INTO combo_raw_materials (combo_id, raw_material_id, qty)
  SELECT ci.combo_id, ci.raw_material_id, ci.qty
  FROM combo_items ci
  WHERE NOT EXISTS (
    SELECT 1
    FROM combo_raw_materials crm
    WHERE crm.combo_id = ci.combo_id
      AND crm.raw_material_id = ci.raw_material_id
  )
  ''',
];
